name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          git config --global user.email "ci@smartcertify.dev"
          git config --global user.name "SmartCertify CI"
          git remote add hf https://user:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/SmartCertify-ML
          git push hf main --force
